/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DummyImport } from "./routes/dummy";

// Create/Update Routes

const DummyRoute = DummyImport.update({
  id: "/dummy",
  path: "/dummy",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/dummy": {
      id: "/dummy";
      path: "/dummy";
      fullPath: "/dummy";
      preLoaderRoute: typeof DummyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/dummy": typeof DummyRoute;
}

export interface FileRoutesByTo {
  "/dummy": typeof DummyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/dummy": typeof DummyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/dummy";
  fileRoutesByTo: FileRoutesByTo;
  to: "/dummy";
  id: "__root__" | "/dummy";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  DummyRoute: typeof DummyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  DummyRoute: DummyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/dummy"
      ]
    },
    "/dummy": {
      "filePath": "dummy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
